# Site settings
title: Ashley Poole
description: 'Engineering Management, Engineering Leadership, Product & Platform Engineering, Site Reliability Engineering Advocate and Speaker.'
intro_description: '- Engineering Leadership -<br />- Engineering Management -<br />- Product & Platform Engineering -<br />- Site Reliability Engineering Advocate -<br />- Speaker -<br />'
url: 'ashleypoole.co.uk'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Ashley Poole'
  email: hello@ashleypoole.co.uk
  twitter_username: 
  facebook_username: 
  github_username:  ashleypoole
  linkedin_username:  ashleypoole

defaults:
  -
    scope:
      path: 'posts'
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'ashleypoole.code-workspace']
