# Site settings
title: Ashley Poole
description: 'Speaker, Engineering Leadership, Site Reliability Engineering Advocate and Co-organiser of @ShropshireDevs user group.'
intro_description: '- Speaker -<br />- Technical Lead -<br />- Co-organiser of <a href="https://twitter.com/shropshiredevs" target="_blank">@ShropshireDevs</a> -<br />- Site Reliability Engineering Advocate -'
url: 'http://localhost:4000'
baseurl: ''
assetsbaseurl: "//assets.ashleypoole.co.uk"
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'ashleypoole'

author:
  name: 'Ashey Poole'
  email: contact@ashleypoole.co.uk
  twitter_username: AshleyPooleUK
  facebook_username: 
  github_username:  AshleyPoole
  linkedin_username:  ashleypoole

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 8
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
